### ISSUE TITLE
Doesn't work together with Fluent module?

### ISSUE THREAD

**Issue by Friksel** [silverstripe/silverstripe-staticpublishqueue#57] opened 2016-12-11 15:48 UTC
I turned an existing website into a static cached website with this module, and everything works great excepts for all translated page-URLs aren't being cached. I'm using the Silverstripe Fluent module. I tried to solve this with yaml config files / config execution order, but so far without any luck :(
Is this module compatible with Silverstripe Fluent? Is there a configurable/easy way to get these modules to work together?

**Comment by tractorcow** [comment] 2016-12-11 21:52
What kind of problems are you experiencing? What kind of static cache is getting generated?

I haven't used this module but, I did write fluent. :)

**Comment by Friksel** [comment] 2016-12-12 10:09
The problem I'm experiencing is that no static cache is being generated for pages in other languages, as translated by Fluent. Pages on the default locale now got cache files rendered, but urls with locales as prefix in the url never get cached. The Fluent module is configured to skip the locale-prefix in the url, so the main url is the same as this would be without using Fluent/translations. That seems to be the reason why the default locale is being cached.
So urls like 'website.com\en\urlsegment' ('en' for English) are not being cached.

**Comment by dhensby** [comment] 2016-12-12 10:55
I'm closing this as a dupe of https://github.com/tractorcow/silverstripe-fluent/issues/244

**Closed by dhensby** 2016-12-12 10:55 UTC

**Comment by wernerkrauss** [comment] 2016-12-12 19:04
yml file won't work, as you always have to adjust static publisher to get all urls you want to build statically.

**Comment by Friksel** [comment] 2016-12-23 17:57
@wernerkrauss Sorry for my late response. I was a little too busy. So far I'm only using the tasks to recreate the full cache. So default behaviour for only sitetree, as provided with the module. And it is working fine, except for the page-translations (by Fluent) having locale-prefixes/locale-urlsegments in the urls. In the code I see special treatment for the translatable module, so I was hoping there was something prepared for FLuent too, 'cause Fluent is developed by a Silverstripe team-member and seems to be very well used. Anyway, thanks for your comment, I'll look into it to have URLs added myself. Or maybe change the cache-loop inside the task.
