### ISSUE TITLE
The build task "StaticCacheFullBuildTask" could not be found

### ISSUE THREAD

**Issue by guci0** [silverstripe/silverstripe-staticpublishqueue#143] opened 2022-09-11 08:02 UTC
Hello World,

I've been trying to make a full static copy (Building static cache for full site) of the site for a while now - I can't seem to do it. The [documentation](https://github.com/silverstripe/silverstripe-staticpublishqueue/blob/5/docs/en/building_the_cache.md), doesn't look right either.

Please help.

---
Fresh SilverStripe 4.11
  - silverstripe/staticpublishqueue 5.2

```
sake dev/tasks/SilverStripe-StaticPublishQueue-Task-StaticCacheFullBuildTask
sake dev/tasks/ProcessJobQueueTask
```

**Comment by GuySartorelli** [comment] 2022-09-12 22:51
Please provide details of what exactly isn't working, what error messages you get, what you have tried to resolve it, etc etc.

**Comment by guci0** [comment] 2022-09-13 05:54
// to delete all
`sake dev/tasks/Symbiote-QueuedJobs-Tasks-DeleteAllJobsTask confirm=1`
// first steep
`sake dev/tasks/SilverStripe-StaticPublishQueue-Task-StaticCacheFullBuildTask`
// fire queue, and there is nothing to cache but...
`sake dev/tasks/ProcessJobQueueTask`
`[2022-09-13 05:34:23] Running Generate static pages for all URLs and others from queue 2.
[2022-09-13 05:34:23] error-log.INFO: count(): Argument #1 ($value) must be of type Countable|array, null given {"exception":"[object] (TypeError(code: 0): count(): Argument #1 ($value) must be of type Countable|array, null given at /.../8.1/test/vendor/silverstripe/staticpublishqueue/src/Job.php:102)"} []`
// but no I check via GitHub StaticCacheFullBuildJob and setup, and there is some different (?), so by hand replace setup function and WORKS! My debugging skills show me that getAllLivePageURLs() was always empty, so after change to:
`$this->URLsToProcess = $this->getAllLivePageURLs();
        $this->URLsToCleanUp = [];
        parent::setup();
        Publisher::singleton()->purgeAll();
        $this->addMessage(sprintf('Building %s URLS', count($this->URLsToProcess)));
        $this->addMessage(var_export(array_keys($this->URLsToProcess), true));`

It's much better, it's error with memory seize limit but /cache **are presents**!

`[2022-09-13 05:39:00] error-log.ALERT: Fatal Error (E_ERROR): Allowed memory size of **134217728** bytes exhausted (tried to allocate 475136 bytes) {"code":1,"message":"Allowed memory size of 134217728 bytes exhausted (tried to allocate 475136 bytes)","file":"/.../8.1/test/vendor/symfony/cache/Traits/FilesystemTrait.php","line":70,"trace":null} []

PHP Fatal error:  Uncaught InvalidArgumentException: "ParentID" is not a field on class "SilverStripe\Assets\Shortcodes\FileLink" in /../8.1/test/vendor/silverstripe/framework/src/ORM/DataObjectSchema.php:111
thrown in /.../8.1/test/vendor/silverstripe/framework/src/ORM/DataObjectSchema.php on line 111
PHP Fatal error:  Unknown: Cannot use output buffering in output buffering display handlers in Unknown on line 0

Fatal error: Unknown: Cannot use output buffering in output buffering display handlers in Unknown on line 0
`
@GuySartorelli I like your help and interest, in the morning I start my day better 👍😉

**Comment by GuySartorelli** [comment] 2022-09-29 02:10
I'm not able to reproduce this from a fresh install of silverstripe cms with this module added. Can you please provide a clear set of step-by-step instructions for how to reproduce this from a fresh install? Please include any composer commands and custom code necessary to reproduce this.

**Comment by GuySartorelli** [comment] 2022-10-04 20:36
Closing in favor of #146 which has more information and seems to be the same problem.

**Closed by GuySartorelli** 2022-10-04 20:36 UTC
Labels: type/bug
