### ISSUE TITLE
All links in cached page appended with ?stage=Live in SS3.7.3

### ISSUE THREAD

**Issue by TomDownard** [silverstripe/silverstripe-staticpublishqueue#102] opened 2019-06-10 10:56 UTC
Any links in pages generated through the Sitetree Link() function are being appended with "?stage=Live" in the cached files. This is an issue for SEO reasons, as the same content is being served on two urls.

For example, when looping through dataobjects in a template:
```
<% loop $Apartments %>
	<a href="$Link">$Title</a>
<% end_loop %>
```
This would result in a URL like: /apartmtent_title?stage=Live being output.

I have tried overriding the Link function in Page.php:
```php
public function Link($action = null) {
	$relativeLink = $this->RelativeLink($action);
	$link = Controller::join_links(Director::baseURL(), $relativeLink);
	$this->extend('updateLink', $link, $action, $relativeLink);
	if(strpos($link, '?stage=Live') !== false){
		$link = str_replace("stage=Live&", "", $link);
		$link = str_replace("stage=Live", "", $link);
	}
	return $link;
}
```

However this results in staged content being included in the cache in loops such as above.

Has anybody come across this issue or a solution for it?

**Comment by mediabeastnz** [comment] 2019-08-25 23:08
+1 also having this issue

**Comment by mediabeastnz** [comment] 2019-08-26 04:57
In the file `URLArrayObject.php` and function `sanitize_url()` there are a few `$_GET` variables unset. Should stage not be added to this e.g.

```
unset($getVars['_ID'], $getVars['_ClassName'], $getVars['stage']);
```

Applying this patch seems to resolve the issue for me but doesn't really touch on why the stage is in the URL in the first place.

**Comment by NightJar** [comment] 2019-09-25 22:14
This is probably a hang over from the alteration to not store global state between requests - it was causing confusion with editors viewing draft content without realising, as there was no indication.

Remember the old days when ?Stage=draft would set a session var, then every request regardless of GET param would always be draft? This might be caused by the job being queued from within the CMS, or is a hangover from ensuring that the live site is cached.

This is all out loud thoughts, in case anyone wants to take a look and maybe submit a PR for [HacktoberFest](https://hacktoberfest.digitalocean.com/) ;)
If so, please see https://docs.silverstripe.org/en/4/contributing/code/ about the SilverStripe process about branching and making PRs against the correct branches :)

I say this because even though the module is marked as supported, this is the SilverStripe 3 compatible version - which is in security support only.

**Comment by emteknetnz** [comment] 2019-12-10 02:32
Possibly related SS3 issue https://github.com/silverstripe/silverstripe-staticpublishqueue/issues/100

**Comment by quamsta** [comment] 2020-09-29 16:14
If anyone is still having an issue with this, I had to implement a hacky fix on an old site we needed to statically generate due to some unexpectedly high traffic to it. In FilesystemPublisher.php, around line 305, I added some code to strip out ?stage=Live in the to-be-saved .html cached file after the if-statment:  "if (Config::inst()->get('FilesystemPublisher', 'include_caching_metadata')) {":

`
			if (Config::inst()->get('FilesystemPublisher', 'include_caching_metadata')) {
				$content = str_replace(
					'</html>',
					sprintf("</html>\n\n", implode(" ", $this->getMetadata($url))),
					$content
				);
			}
			$content = str_replace(
				'?stage=Live',
				'',
				$content
			);`

**Comment by dhensby** [comment] 2021-05-20 23:51
I'm not sure if this is fixed, but I'm afraid v3 is out of support now

**Closed by dhensby** 2021-05-20 23:51 UTC
Labels: affects/v3, change/patch, effort/medium, impact/high, type/bug
